### ISSUE TITLE
useNewUrlParser, useUnifiedTopology, useFindAndModify, and useCreateIndex are no longer supported options.

### ISSUE THREAD

**Issue by Vijay-K-2003** [iiitv/CTF-Backend#10]
### config/database.js line 7 to 10 are no more required.
![image](https://user-images.githubusercontent.com/75903092/135681294-df13bee5-29dc-45d7-9c62-a4b4a3ee6f7d.png)

**Comment by Vijay-K-2003** [comment]
Please assign me this under contribute-a-thon

**Comment by Shreyansh-Mishra** [comment]
GFI @Vijay-K-2003

**Comment by Vijay-K-2003** [comment]
### I have this problem while pushing. Could you please help me to resolve this.
I have already tried git pull.
![image](https://user-images.githubusercontent.com/75903092/135710030-ac5ab9ab-d0ed-4dfc-87fa-bce839a1045c.png)

**Comment by Shreyansh-Mishra** [comment]
There have been some changes since new PRs were merged, try running git pull in the terminal and pushing changes once you've done that.
