### ISSUE TITLE
Login only if verification status is Active else send an email and ask the user to verify email.

### ISSUE THREAD

**Issue by batflarrow** [iiitv/CTF-Backend#13]

**Comment by saivasanth528** [comment]
Hi, I have gone through the WIKI and other stuff. I have some questions
1. How you have done the process of email verification  ?
2. Is there any expiry for the email verification process , I mean how long the verification email will be valid, usually it will be for two days
3.  On your issue, my understanding was before we allow any user to log in, we have to check the verification stage if not , we have to send an email to verify the email , assuming verify email was sent previously ?

**Comment by batflarrow** [comment]
> Hi, I have gone through the WIKI and other stuff. I have some questions
> 
> 1. How you have done the process of email verification  ?
> 2. Is there any expiry for the email verification process , I mean how long the verification email will be valid, usually it will be for two days
> 3. On your issue, my understanding was before we allow any user to log in, we have to check the verification stage if not , we have to send an email to verify the email , assuming verify email was sent previously ?

1. Email verification has been implemented during the process of signup itself 
2. Currently expiry for email verification is for 7 days.
3. No this verification step is during the login if the user has signed up but the email is not yet verified. And even if an email was sent earlier, another email has to be sent in case of non-verification.

Hope this answers your queries feel free to reach out if not :)

**Comment by saivasanth528** [comment]
1. Is there any dedicated front end for this , or in this repo only that was maintained, I was able to see only one index.html.
2. Is the application deployed anywhere?
3. And this work involves seeing the UI experience also, like how the error message is displayed to the end user , if he didn't verify the email or you guys concentrating on just backend and checking everything with postman ?

**Comment by DevParmar1** [comment]
I can solve it!

**Comment by batflarrow** [comment]
> I can solve it!

GFI @DevParmar1
