### ISSUE TITLE
Create Authorization middleware for the APIs

### ISSUE THREAD

**Issue by batflarrow** [iiitv/CTF-Backend#3]

**Comment by DevParmar1** [comment]
@prathmeshkhandelwal1 @batflarrow can I work on this issue?

**Comment by DevParmar1** [comment]
Can I make a PR over here too? I've solved this issue. @batflarrow  @prathmeshkhandelwal1

**Comment by Shreyansh-Mishra** [comment]
GFI @DevParmar1

**Comment by DevParmar1** [comment]
how do you want to store & authenticate tokens? via headers or cookies? after login

**Comment by batflarrow** [comment]
> how do you want to store & authenticate tokens? via headers or cookies? after login

Tokens are stored in HTTP only cookie so for the middleware you will get the token in cookies. You may look at the login route, which has already been implemented if you have any doubts.

**Comment by DevParmar1** [comment]
But as in general auth tokens are stored in the header, so I have implemented it that way. I can change it to cookies if you want but just review it once as I think it would be better this way.

**Comment by batflarrow** [comment]
> But as in general auth tokens are stored in the header, so I have implemented it that way. I can change it to cookies if you want but just review it once as I think it would be better this way.

For tokens to be sent in headers they'll have to be stored in local storage on the browser or some other storage which are vulnerable to xss attack as well as accessible via javascript whereas an HTTP only cookie is secure in that terms of being accessed by client-side javascript but they are still vulnerable to xss, there is a tradeoff here and they and ultimately it boils down to personal preference, and this time I chose HTTP-only cookie for this matter. Also, an even better solution would be to store the access token in local storage and refresh token in http-only cookie but it might be a little overkill for this project.

**Comment by DevParmar1** [comment]
Alright, I've done the changes review it.
