### ISSUE TITLE
Create endpoints for CRUD operations on question database

### ISSUE THREAD

**Issue by Shreyansh-Mishra** [iiitv/CTF-Backend#4]

**Comment by JoelLau** [comment]
hi @Shreyansh-Mishra , can i take up this issue?

**Comment by Shreyansh-Mishra** [comment]
GFI @JoelLau 👍🏽

**Comment by JoelLau** [comment]
@Shreyansh-Mishra is the _id_ field in the question model (`models/question.js`) is meant to be input by the user?

**Comment by Shreyansh-Mishra** [comment]
Yes, the admin will assign an id to the question while creating one
