### ISSUE TITLE
Add the functionality to change and reset a user's password

### ISSUE THREAD

**Issue by Shreyansh-Mishra** [iiitv/CTF-Backend#5]

**Comment by tfarnecim** [comment]
Hey, can i work on it?

**Comment by NicolasBiondini** [comment]
Give me this issue, i can make it!

**Comment by Shreyansh-Mishra** [comment]
GFI @NicolasBiondini 👍

**Comment by NicolasBiondini** [comment]
I just started and i'm triying to make it, but it's gonna be much simple if someone make a PR of the login functionality and the JWT.

**Comment by batflarrow** [comment]
> I just started and i'm triying to make it, but it's gonna be much simple if someone make a PR of the login functionality and the JWT.

Yeah sure one PR is under review for the login functionality it will be merged soon.

**Comment by batflarrow** [comment]
> I just started and i'm triying to make it, but it's gonna be much simple if someone make a PR of the login functionality and the JWT.

It's done now you may go ahead with the issue :)

**Comment by DevParmar1** [comment]
Is this issue still open?

**Comment by batflarrow** [comment]
> Is this issue still open?

Yeah sure are you up for it?

**Comment by DevParmar1** [comment]
Yeah sure. How do you want to reset, via mail reset or just a classic reset interface?

**Comment by batflarrow** [comment]
Basically You need to create two apis one will be the protected api which will be used for changing the password of a user when he's logged in and for reset password api it will be the classic email reset api.

**Comment by DevParmar1** [comment]
Ok, I'll do it!

**Comment by batflarrow** [comment]
> Ok, I'll do it!

Go for it @DevParmar1

**Comment by DevParmar1** [comment]
Done!
